### ISSUE TITLE
EIP-155 not implemented on Ledger driver

### ISSUE THREAD

**Issue by kayagoban** [kayagoban/shadowlands-core#2]
After reviewing the ledger driver, I'm convinced that the transactions it generates are vulnerable to replay attacks.  

I've been reading EIP-155 all day, as well as go-ethereum implementations of the ledger driver, and the web3.py eth_account submodule.  I know I need to mutate the v based on the formula given in EIP155, but the exact order of operations is escaping me.  I need to talk to an expert.  @carver, would you be willing to chat with me about your implementation of EIP-155 on eth_account?

**Comment by carver** [comment]
Sure. Instead of signing [the unsigned transaction rlp](https://github.com/ethereum/eth-account/blob/f71fff0b6e4cdc2321b908761419c9afbaeed175/eth_account/internal/transactions.py#L160-L167), you sign the [signed transaction RLP](https://github.com/ethereum/eth-account/blob/f71fff0b6e4cdc2321b908761419c9afbaeed175/eth_account/internal/transactions.py#L170-L175), where the [`v` is the chain_id, and `r` and `s` are 0](https://github.com/ethereum/eth-account/blob/f71fff0b6e4cdc2321b908761419c9afbaeed175/eth_account/internal/transactions.py#L146-L152).

Then you [strip the `v`, `r`, and `s` back out](https://github.com/ethereum/eth-account/blob/f71fff0b6e4cdc2321b908761419c9afbaeed175/eth_account/internal/transactions.py#L53-L54) and sign it like normal, but with one more change: a modified `v`: [`v_raw + 35 + 2 * chain_id`](https://github.com/ethereum/eth-account/blob/f71fff0b6e4cdc2321b908761419c9afbaeed175/eth_account/internal/signing.py#L109-L114) , where `v_raw` is 0 or 1, as output from the EC signing libraries.

Happy to continue here or on gitter.im or email.

**Comment by kayagoban** [comment]
> Instead of signing the unsigned transaction rlp, you sign the signed transaction RLP, where the v is the chain_id, and r and s are 0.

So far I am already doing this part, in imitation of the go-ethereum implementation.  I have some kind of suspicion that I am fouling up the addition of the v + r + s to the existing encoded RLP.

            encodedTx = rlp.encode(tx, UnsignedTransaction)
            # Append network ID
            encodedTx += int(cls.eth_node._network).to_bytes(1, 'big')
            encodedTx += int(0).to_bytes(1, 'big')
            encodedTx += int(0).to_bytes(1, 'big')


In the case of Kovan = 42, this is what the ledger spits out:

(Pdb) _v
120
(Pdb) _r
32795273583791385058108126648205473907365790568796597567247212171709843696258
(Pdb) _s
18659385064427538730925731734609477208114325244744185023860649802417900448582
(Pdb) extract_chain_id(_v)
(42, 28)
(Pdb) to_eth_v(_v)
147
(Pdb) len(result)
65


That actually looks really close to what I would expect if the Ledger hardware was implementing EIP155 internally.  However, I do see this when I try to
submit the tx:


rx = self.w3.eth.sendRawTransaction(signed_tx.rawTransaction)
  File "/Users/cthomas/.shadowlands/lib/python3.7/site-packages/web3/eth.py", line 274, in sendRawTransaction
    [raw_transaction],
  File "/Users/cthomas/.shadowlands/lib/python3.7/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error”)
ValueError: {'code': -32010, 'message': 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 50239999999900000 and got: 0.’}

I have to think that the client believes I’m trying to send ether from another chain, where my account has 0 ether.


> Then you strip the v, r, and s back out and sign it like normal, but with one more change: a modified v: v_raw + 35 + 2 * chain_id , where v_raw is 0 or 1, as output from the EC signing libraries.

I have to think that the folks at ledger didn’t intend for the users to need to approve transactions twice.  Did I use the right method to append to the rlp byte array?  Wondering if that’s the culprit.

**Comment by carver** [comment]
> I have some kind of suspicion that I am fouling up the addition of the v + r + s to the existing encoded RLP.
> 
            encodedTx = rlp.encode(tx, UnsignedTransaction)
            # Append network ID
            encodedTx += int(cls.eth_node._network).to_bytes(1, 'big')
            encodedTx += int(0).to_bytes(1, 'big')
            encodedTx += int(0).to_bytes(1, 'big')

Yeah, you don't want to rlp encode and then add the data, that will mess with the length prefixing. Add the v, r, and s to a `SignedTransaction` then `rlp.encode` it. But it doesn't look like it matters, because...

> That actually looks really close to what I would expect if the Ledger hardware was implementing EIP155 internally.

Yeah, that's already implementing it. If `v` is anything >=35, then it's EIP-155 already.

> I have to think that the client believes I’m trying to send ether from another chain, where my account has 0 ether.

If you have the raw transaction available, you can check what the sender is with https://eth-account.readthedocs.io/en/latest/eth_account.html#eth_account.account.Account.recoverTransaction

**Comment by kayagoban** [comment]
Okay, maybe I hosed the length prefixing, and the path derivation  paid the price for my hubris.

Thanks for the pointers.

BTW, shadowlands should should be accepting pass phrases for the trezor as of this morning’s commit, if you want to give it another stab.

**Comment by carver** [comment]
Yup, I'm in, thanks! I was able to see multiple derived addresses, and reverse ENS lookups. Next up is to try a transfer on ropsten (or maybe a network that's a little less borked). Then I want to figure out how dapps work so that I can actually tinker with contracts.

- Is there anything like https://mycrypto.com/contracts/interact available?
- Where would be the best place to learn about writing a pydapp? (even if it's in the source code or a sloppy example, and the API is incomplete, no problem)

I know this is severely OT. Any chance you're interested in setting up a gitter room for casual questions? It feels a little overkill to open two issues about the above. :)

**Comment by kayagoban** [comment]
A gitter sounds like a good idea, there needs to be some forum for talking...   I don’t care for reddit much anymore, so gitter sounds good.

I just got rinkeby kinda-working a few days ago by injecting the geth PoA middleware.  Haven’t played with it much.  Good experiences with Kovan though.

If you use websockets to connect, prepare yourself for some weird, random shit when the jsonrpc function cache bug hits you.

My repo https://github.com/kayagoban/example-dapps-shadowlands contains my ens manager dapp - that’s the only existing example so far.

The API is incomplete and there’s no documentation yet.  All slated for the alpha release.

Here’s a little easter egg: when running a dapp, you can ctrl-d to drop into pdb and look around, then continue to get back into the dapp.

On debugging break points: it’s necessary to use an incantation debug(); pdb.set_trace() to break out of ncurses.  You’ll see it plastered all over the place in the code.

**Comment by kayagoban** [comment]
Fixed by https://github.com/kayagoban/shadowlands-core/commit/b8b174efc978436512a49a8f866b71bd30a28229
